
#hibernate:
#  cache:
#    queries: false
#    use_second_level_cache: false
#    use_query_cache: false

hibernate.groovy.enabled: true

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  dbCreate: update
  url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

